name: legacy_wifi_check
dependencies:
- python=3.5
- pip
- pip:
  - absl-py==0.4.1
  - astor==0.7.1
  - certifi==2018.8.24
  - click==7.1.2
  - Cython==0.29.21
  - databricks-connect==5.5.3
  - gast==0.4.0
  - grpcio==1.12.1
  - h5py==2.8.0
  - joblib==0.14.1
  - Keras==2.2.2
  - Keras-Applications==1.0.4
  - Keras-Preprocessing==1.0.2
  - Markdown==2.6.11
  - nltk==3.5
  - numpy==1.14.2
  - pandas==0.20.3
  - protobuf==3.6.0
  - py4j==0.10.7
  - pystan==2.19.1.1
  - python-dateutil==2.8.1
  - pytz==2020.1
  - PyYAML==3.13
  - regex==2018.8.29
  - scikit-learn==0.20.0
  - scipy==1.1.0
  - six==1.15.0
  - tensorboard==1.10.0
  - tensorflow==2.3.0
  - termcolor==1.1.0
  - tqdm==4.49.0
  - Werkzeug==1.0.1

